"""
Alternative login: Use this if you're already logged into the frontend.
This will help you get your Firebase token from the browser.
"""

print("=" * 60)
print("🔑 Alternative Login Method - Get Token from Frontend")
print("=" * 60)
print()
print("Since the Firebase API key may have restrictions, here's how to login:")
print()
print("METHOD 1: Login via Frontend (Recommended)")
print("=" * 60)
print("1. Start the frontend: cd frontend && npm run dev")
print("2. Open browser: http://localhost:5173")
print("3. Login with credentials:")
print("   - Email: 99999@ousl.edu.lk")
print("   - Password: 999999")
print("4. Open browser console (F12)")
print("5. Run this command:")
print()
print("   firebase.auth().currentUser.getIdToken().then(token => {")
print("      console.log('TOKEN:', token);")
print("      // Copy this token")
print("   });")
print()
print("6. Copy the token and create C:\\AI_Prints\\auth_token.txt:")
print()
print("   {")
print('     "token": "PASTE_TOKEN_HERE",')
print('     "user_id": "99999",')
print('     "role": "user",')
print('     "email": "99999@ousl.edu.lk"')
print("   }")
print()
print("=" * 60)
print()
print("METHOD 2: Temporary Bypass (For Testing Only)")
print("=" * 60)
print("Set REQUIRE_AUTH = False in virtual_printer_agent.py")
print("This will disable authentication enforcement temporarily.")
print()
print("=" * 60)
input("\nPress Enter to close...")
